import type { Metadata } from "next";
import { getServerAuthSession } from "@/lib/auth";
import Navbar from "@/components/ui/Navbar";



export const metadata: Metadata = {
  title: "TuneCraft",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerAuthSession();
  return (
    <html lang="en">
      <body>
        <Navbar email={session?.user.email}/>
        {children}
        </body>
    </html>
  );
}
