import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create New Song",
    description: "Generated by create next app",
  };


export default function SongLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body>
            {children}
          </body>
      </html>
    );
  }